"""initial tables

Revision ID: 07c8a3a5cc1c
Revises: 
Create Date: 2026-03-28 10:32:03.419795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07c8a3a5cc1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('universe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capital_allocated', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('candles',
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'exchange', 'timeframe', 'time')
    )
    op.create_index('ix_candles_lookup', 'candles', ['symbol', 'exchange', 'timeframe', 'time'], unique=False)
    op.create_table('daily_snapshots',
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pnl_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'date', name='uq_agent_date')
    )
    op.create_table('positions',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'symbol', 'exchange', 'side', name='uq_open_position')
    )
    op.create_table('trades',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('product', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=50), nullable=True),
    sa.Column('fill_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('brokerage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('signal_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('positions')
    op.drop_table('daily_snapshots')
    op.drop_index('ix_candles_lookup', table_name='candles')
    op.drop_table('candles')
    op.drop_table('agents')
    # ### end Alembic commands ###
