"""Gemini API reasoning agent — validates and enriches signals from other agents."""

import json
import re

import google.generativeai as genai
import structlog

from app.agents.base import BaseAgent
from app.agents.signals import MarketSnapshot, Signal
from app.config import settings

log = structlog.get_logger()


def _parse_gemini_json(text: str) -> dict:
    """Parse JSON from Gemini response, handling markdown wrappers and truncation."""
    # Strip markdown code block wrapper
    text = re.sub(r"^```(?:json)?\s*\n?", "", text.strip())
    text = re.sub(r"\n?```\s*$", "", text.strip())

    # Try direct parse first
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Find the first { and try to parse from there
    start = text.find("{")
    if start == -1:
        raise ValueError("No JSON object found")
    substr = text[start:]
    try:
        return json.loads(substr)
    except json.JSONDecodeError:
        pass

    # JSON is truncated — extract key fields with regex
    result = {}
    validation = re.search(r'"validation"\s*:\s*"(\w+)"', substr)
    if validation:
        result["validation"] = validation.group(1)
    confidence = re.search(r'"adjusted_confidence"\s*:\s*([\d.]+)', substr)
    if confidence:
        result["adjusted_confidence"] = float(confidence.group(1))
    reasoning = re.search(r'"reasoning"\s*:\s*"((?:[^"\\]|\\.)*)', substr)
    if reasoning:
        result["reasoning"] = reasoning.group(1)[:500]
    result["risk_flags"] = []
    sl = re.search(r'"suggested_stop_loss"\s*:\s*([\d.]+|null)', substr)
    result["suggested_stop_loss"] = float(sl.group(1)) if sl and sl.group(1) != "null" else None
    tp = re.search(r'"suggested_take_profit"\s*:\s*([\d.]+|null)', substr)
    result["suggested_take_profit"] = float(tp.group(1)) if tp and tp.group(1) != "null" else None

    if "validation" not in result or "adjusted_confidence" not in result:
        raise ValueError("Could not extract required fields from truncated JSON")
    return result


SYSTEM_PROMPT = """You are a quantitative trading analyst for Indian stock markets (NSE/BSE).
Your role is to validate trading signals generated by technical and sentiment analysis agents.
Be concise, data-driven, and conservative. Flag risks clearly. Always respond in valid JSON."""

SIGNAL_PROMPT_TEMPLATE = """\
A trading signal has been generated. Analyze it and provide your assessment.

SIGNAL: {action} {symbol} on {exchange}
CONFIDENCE: {confidence:.2f}
ENTRY PRICE: ₹{entry_price:,.2f}
STOP LOSS: ₹{stop_loss:,.2f}
TAKE PROFIT: ₹{take_profit:,.2f}

TECHNICAL INDICATORS:
{indicators}

RECENT PRICE ACTION (daily OHLCV, last 2 days):
{candle_data}

AGENT REASONING: {agent_reasoning}

CURRENT PORTFOLIO CONTEXT:
{portfolio_context}

Respond in JSON:
{{
  "validation": "AGREE" | "DISAGREE" | "MODIFY",
  "adjusted_confidence": <float 0.0-1.0>,
  "reasoning": "<detailed explanation>",
  "risk_flags": ["<list of concerns if any>"],
  "suggested_stop_loss": <float or null>,
  "suggested_take_profit": <float or null>
}}"""


class ReasoningAgent(BaseAgent):
    """Uses Gemini API to validate and enrich signals from other agents.

    Called ONLY when a technical or sentiment agent generates a signal.
    Acts as a "second opinion" — never generates signals independently.
    """

    def __init__(self, agent_id: str, name: str, config: dict):
        super().__init__(agent_id, name, config)
        self.temperature = config.get("temperature", 0.3)
        genai.configure(api_key=settings.gemini_api_key)
        self.model = genai.GenerativeModel(
            model_name=settings.gemini_model,
            system_instruction=SYSTEM_PROMPT,
            generation_config=genai.GenerationConfig(
                temperature=self.temperature,
                max_output_tokens=2048,
                response_mime_type="application/json",
            ),
        )

    async def analyze(self, snapshot: MarketSnapshot) -> Signal | None:
        """ReasoningAgent doesn't analyze snapshots directly.
        Use validate_signal() instead.
        """
        return None

    async def validate_signal(
        self,
        signal: Signal,
        snapshot: MarketSnapshot,
        portfolio_context: str = "No open positions.",
    ) -> dict:
        """Validate a signal using Gemini API.

        Returns dict with: validation, adjusted_confidence, reasoning,
        risk_flags, suggested_stop_loss, suggested_take_profit
        """
        prompt = self._build_prompt(signal, snapshot, portfolio_context)

        try:
            response = await self.model.generate_content_async(prompt)

            text = response.text
            result = _parse_gemini_json(text)

            usage = response.usage_metadata
            self.log.info(
                "gemini_validation",
                symbol=signal.symbol,
                validation=result.get("validation"),
                adjusted_confidence=result.get("adjusted_confidence"),
                input_tokens=getattr(usage, "prompt_token_count", 0),
                output_tokens=getattr(usage, "candidates_token_count", 0),
            )
            return result

        except (json.JSONDecodeError, ValueError):
            self.log.error("gemini_invalid_json", response=text[:200])
            return self._fallback_response(signal)
        except Exception as e:
            self.log.error("gemini_api_error", error=str(e))
            return self._fallback_response(signal)

    def get_config_schema(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "model": {"type": "string", "default": "gemini-2.0-flash"},
                "temperature": {"type": "number", "default": 0.3, "minimum": 0, "maximum": 1},
            },
        }

    # ── Private helpers ──

    def _build_prompt(
        self,
        signal: Signal,
        snapshot: MarketSnapshot,
        portfolio_context: str,
    ) -> str:
        # Compressed: only include votes and key indicators (not all raw values)
        meta = signal.metadata or {}
        votes = meta.get("votes", {})
        indicators_lines = []
        if votes:
            for indicator, vote in votes.items():
                vote_label = "+1 bullish" if vote > 0 else "-1 bearish" if vote < 0 else "0 neutral"
                indicators_lines.append(f"  {indicator}: {vote_label}")
        # Add only the most relevant raw values
        for key in ["rsi", "macd", "atr"]:
            val = meta.get(key)
            if val is not None:
                indicators_lines.append(
                    f"  {key}: {val:.2f}" if isinstance(val, float) else f"  {key}: {val}"
                )
        indicators = "\n".join(indicators_lines) if indicators_lines else "  No indicator data"

        # Only last 2 candles instead of 5
        candles = snapshot.candles_1d[-2:] if snapshot.candles_1d else []
        candle_lines = []
        for c in candles:
            candle_lines.append(
                f"  O:{c.get('open', 'N/A')} H:{c.get('high', 'N/A')} "
                f"L:{c.get('low', 'N/A')} C:{c.get('close', 'N/A')} V:{c.get('volume', 'N/A')}"
            )
        candle_data = "\n".join(candle_lines) if candle_lines else "  No recent data"

        return SIGNAL_PROMPT_TEMPLATE.format(
            action=signal.action,
            symbol=signal.symbol,
            exchange=signal.exchange,
            confidence=signal.confidence,
            entry_price=signal.entry_price,
            stop_loss=signal.stop_loss,
            take_profit=signal.take_profit,
            indicators=indicators,
            candle_data=candle_data,
            agent_reasoning=signal.reasoning[:200] if signal.reasoning else "N/A",
            portfolio_context=portfolio_context,
        )

    def _fallback_response(self, signal: Signal) -> dict:
        """Return a neutral fallback when Gemini is unavailable."""
        return {
            "validation": "AGREE",
            "adjusted_confidence": signal.confidence,
            "reasoning": "Gemini API unavailable — passing signal through unchanged.",
            "risk_flags": ["llm_unavailable"],
            "suggested_stop_loss": None,
            "suggested_take_profit": None,
        }
